language: php

sudo: false

php:
- 5.3
- 5.4
- 5.5
- 5.6

env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.6 WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.4 WP_MULTISITE=0
  global:
    secure: HiPTPBaYNi1WkOXiacGKtksl8OIrA3Ul0iM9rWwPFD+lwGrs0UPZqr7vVsrhWBrbiEEypYTceFcGiLtabUxSh77g37XjpcbOYQAfEOiaLHIQrrq+qtzi0P+YGeJmnCuJUtdCRIM2GzCdXtLojBIxresjkoX43bzYkc8EMPr2Yk14FKceh1sU4JCfu/gfvbm2UBjcEWWkhQhCwAapLjFxUbv5FzaSbRoYqztbmMxa2431B+iAeh7mANGl8MFvVxwnb3NsUhItOGd/jkh9oCSNzcWb8kZplsFAKfxDyKB+TUjf/YM1zuItyhgx1/bdz+BEQRiI6uPUSADzQrfoRvtERoeBtRlH/jtg9HzNBYpk3zXztvOQKmAvRc6V+vbIX1rEX7UL/4OhVmoUf+G6aNZ1BKVP7wdMUJXuj3gyI7TImxQkPJUrgtZekYwBlSNbnQQdlogntKJFcrd4mB2tjsn0HMp/Gqd8lQkbsU/JzidQ/zEG0qeGozq+Sk41ofRkS3XDQ5VZwckPrFXQoQq732jVnLu4Xazi1sZruw8n3BE7zcSAEPoyA4G1MtGwmeiflsWDRL7qU+RITe8pXUifFqsYFMnyCHScT3CNJnjODCBBtG3PWpFhlQ84SMZQvww0k459nhHnIcjXw0DvKTTg17nD0oDw3bnRwCwnojw1VFmFh3E=
matrix:
  include:
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=1
  exclude:
  - php: hhvm
    env: WP_VERSION=4.0 WP_MULTISITE=0
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- |
  # Install the specified version of PHPUnit depending on the PHP version:
  if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
    case "$TRAVIS_PHP_VERSION" in
      7.1|7.0|hhvm|nightly)
        echo "Using PHPUnit 5.7"
        composer global require "phpunit/phpunit=5.7.*"
        ;;
      5.6|5.5|5.4|5.3)
        echo "Using PHPUnit 4.8"
        composer global require "phpunit/phpunit=4.8.*"
        ;;
      5.2)
        # Do nothing, use default PHPUnit 3.6.x
        echo "Using default PHPUnit, hopefully 3.6"
        ;;
      *)
        echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
        exit 1
        ;;
    esac
  fi

script:
- if [[ $TRAVIS_PHP_VERSION != 'hhvm' && ( $TRAVIS_PHP_VERSION != '5.5'|| $WP_VERSION != 'latest'
  || $WP_MULTISITE != '0' ) ]]; then phpenv config-rm xdebug.ini; fi
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi

after_script:
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
  fi
